name: jokebook
description: A new Flutter application.


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.3
  flutter_spinkit: "^4.1.2"
  animated_text_kit: ^4.2.1
  animated_button: ^0.2.0
  connectivity_plus: "^1.0.1"

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.9
  build_runner: ^2.0.4

flutter:

  uses-material-design: true
  fonts:
   - family: Travis-Zone
     fonts:
       - asset: lib/fonts/Travis-Zone.ttf
   - family: spider-king-regular
     fonts:
       - asset: lib/fonts/spider-king-regular.ttf

